name: project_big_data
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - _python_abi3_support=1.0=hd8ed1ab_2
  - asttokens=3.0.1=pyhd8ed1ab_0
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.12.2=h06a4308_0
  - comm=0.2.3=pyhe01879c_0
  - cpython=3.12.12=py312hd8ed1ab_1
  - debugpy=1.8.19=py312h372c3de_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.3=h7354ed3_4
  - ipykernel=7.1.0=pyha191276_0
  - ipython=9.8.0=pyh53cf698_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.7.0=pyhcf101f3_0
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libexpat=2.7.3=h7354ed3_4
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgomp=15.2.0=h4751f2c_7
  - libnsl=2.0.0=h5eee18b_0
  - libsodium=1.0.20=h4ab18f5_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - ncurses=6.5=h7934f7d_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=3.6.0=h26f9b46_0
  - packaging=25.0=pyh29332c3_1
  - parso=0.8.5=pyhcf101f3_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pip=25.3=pyhc872135_0
  - platformdirs=4.5.1=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.2.0=py312h5253ce2_0
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.12.12=hd17a9e1_1
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-gil=3.12.12=hd8ed1ab_1
  - python_abi=3.12=3_cp312
  - pyzmq=27.1.0=py312hfb55c3c_0
  - readline=8.3=hc2a1206_0
  - setuptools=80.9.0=py312h06a4308_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.51.0=h2a70700_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.15=h54e0aa7_0
  - tornado=6.5.4=py312h961da02_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=py312h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zeromq=4.3.5=h387f397_9
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - cloudpickle==3.1.2
      - contourpy==1.3.3
      - cycler==0.12.1
      - fonttools==4.61.1
      - imageio==2.37.2
      - joblib==1.5.3
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - lime==0.2.0.1
      - llvmlite==0.46.0
      - matplotlib==3.10.8
      - networkx==3.6.1
      - numba==0.63.1
      - numpy==2.3.0
      - nvidia-nccl-cu12==2.29.2
      - pandas==2.3.3
      - pillow==12.0.0
      - pyparsing==3.3.1
      - pytz==2025.2
      - scikit-image==0.26.0
      - scikit-learn==1.8.0
      - scipy==1.16.3
      - seaborn==0.13.2
      - shap==0.50.0
      - slicer==0.0.8
      - threadpoolctl==3.6.0
      - tifffile==2026.1.14
      - tqdm==4.67.1
      - tzdata==2025.3
      - xgboost==3.1.3
prefix: /home/miki/anaconda3/envs/project_big_data
